---
- name: Install and Configure Jenkins
  hosts: jenkins
  become: yes
  tasks:
    - name: Ensure all packages are updated
      apt:
        update_cache: yes

    - name: Install required dependencies
      apt:
        name: curl
        state: present

    - name: Add the Jenkins GPG key
      command: >
        curl -fsSL https://pkg.jenkins.io/debian/jenkins.io-2023.key | tee /usr/share/keyrings/jenkins-keyring.asc
      args:
        creates: /usr/share/keyrings/jenkins-keyring.asc

    - name: Add the Jenkins repository
      copy:
        content: |
          deb [signed-by=/usr/share/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian-stable binary/
        dest: /etc/apt/sources.list.d/jenkins.list

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install Jenkins
      apt:
        name: jenkins
        state: present

    - name: Ensure Jenkins is running and enabled
      service:
        name: jenkins
        state: started
        enabled: yes
